FROM python:3.9-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0

# Install Python dependencies
COPY requirements/dev.txt .
RUN pip install -r dev.txt

# Copy application code
COPY . .

# Set environment variables
ENV FLASK_APP=deployment/serving/flask_app.py
ENV FLASK_ENV=development
ENV PYTHONPATH=/app

# Expose ports
EXPOSE 5000 6006

CMD ["flask", "run", "--host=0.0.0.0"]
